### ISSUE TITLE
Omnidirectional walking

### ISSUE THREAD

**Issue by yepw** [zainkhan-afk/Quadrupedal-Robot-Gait-Visualization#3]
Thank you for providing this interesting visualization tool. I wonder whether it's possible (or how easy to extend the current code) to achieve omnidirectional walking, i.e., the quadrupedal robot can not only move forward, but also left right, or diagonally.

**Comment by zainkhan-afk** [comment]
Hi
Thank you for showing interest in the code.
It is possible and quite easy to integrate omnidirectional walking. If you look at the _TimingGait_ class inside the _gaits.py_ file, you will find that the X and Z position of the gait are variable while the Y position is fixed, you can change the rate at which X and Y change to achieve a gait in any direction. 

However, visually showing the ground moving in the correct direction is going to require some work, it will not be that straight forward.

**Comment by yepw** [comment]
Thank you for your reply. We will try what you said.

**Comment by zainkhan-afk** [comment]
Hi, have a look at the _3-omnidirectional-walking_ branch. I implemented the omnidirectional gait, you can change the robot heading using the "a" and "d" keys.

**Comment by yepw** [comment]
Wow, thanks! The new branch is very helpful!
